export const MEASUREMENTS_PER_SCALE_REQUEST = 'MEASUREMENTS_PER_SCALE_REQUEST';
export const MEASUREMENTS_PER_SCALE_SUCCESS = 'MEASUREMENTS_PER_SCALE_SUCCESS';
export const MEASUREMENTS_PER_SCALE_FAIL = 'MEASUREMENTS_PER_SCALE_FAIL';
