export const MEASUREMENTS_PER_SCALE_REQUEST = 'MEASUREMENTS_PER_SCALE_REQUEST';
export const MEASUREMENTS_PER_SCALE_SUCCESS = 'MEASUREMENTS_PER_SCALE_SUCCESS';
export const MEASUREMENTS_PER_SCALE_FAIL = 'MEASUREMENTS_PER_SCALE_FAIL';

export const GET_FILTERED_DATA_REQUEST = 'GET_FILTERED_DATA_REQUEST';
export const GET_FILTERED_DATA_SUCCESS = 'GET_FILTERED_DATA_SUCCESS';
export const GET_FILTERED_DATA_FAIL = 'GET_FILTERED_DATA_FAIL';
