export const LIST_SCALES_REQUEST = 'LIST_SCALES_REQUEST';
export const LIST_SCALES_SUCCESS = 'LIST_SCALES_SUCCESS';
export const LIST_SCALES_FAIL = 'LIST_SCALES_FAIL';

export const GET_SINGLE_SCALE_REQUEST = 'GET_SINGLE_SCALE_REQUEST';
export const GET_SINGLE_SCALE_SUCCESS = 'GET_SINGLE_SCALE_SUCCESS';
export const GET_SINGLE_SCALE_FAIL = 'GET_SINGLE_SCALE_FAIL';
