export const LIST_SCALES_REQUEST = 'LIST_SCALES_REQUEST';
export const LIST_SCALES_SUCCESS = 'LIST_SCALES_SUCCESS';
export const LIST_SCALES_FAIL = 'LIST_SCALES_FAIL';

export const GET_SCALE_BY_ID_REQUEST = 'GET_SCALE_BY_ID_REQUEST';
export const GET_SCALE_BY_ID_SUCCESS = 'GET_SCALE_BY_ID_SUCCESS';
export const GET_SCALE_BY_ID_FAIL = 'GET_SCALE_BY_ID_FAIL';
