export const GET_ALL_OPERATORS_REQUEST = 'GET_ALL_OPERATORS_REQUEST';
export const GET_ALL_OPERATORS_SUCCESS = 'GET_ALL_OPERATORS_SUCCESS';
export const GET_ALL_OPERATORS_FAIL = 'GET_ALL_OPERATORS_FAIL';

export const GET_OPERATOR_BY_ID_REQUEST = 'GET_OPERATOR_BY_ID_REQUEST';
export const GET_OPERATOR_BY_ID_SUCCESS = 'GET_OPERATOR_BY_ID_SUCCESS';
export const GET_OPERATOR_BY_ID_FAIL = 'GET_OPERATOR_BY_ID_FAIL';

export const OPERATOR_BY_ID_UPDATE_REQUEST = 'OPERATOR_BY_ID_UPDATE_REQUEST';
export const OPERATOR_BY_ID_UPDATE_SUCCESS = 'OPERATOR_BY_ID_UPDATE_SUCCESS';
export const OPERATOR_BY_ID_UPDATE_FAIL = 'OPERATOR_BY_ID_UPDATE_FAIL';
export const OPERATOR_BY_ID_UPDATE_RESET = 'OPERATOR_BY_ID_UPDATE_RESET';

export const CREATE_OPERATOR_REQUEST = 'CREATE_OPERATOR_REQUEST';
export const CREATE_OPERATOR_SUCCESS = 'CREATE_OPERATOR_SUCCESS';
export const CREATE_OPERATOR_FAIL = 'CREATE_OPERATOR_FAIL';
