export const GET_ALL_OPERATORS_REQUEST = 'GET_ALL_OPERATORS_REQUEST';
export const GET_ALL_OPERATORS_SUCCESS = 'GET_ALL_OPERATORS_SUCCESS';
export const GET_ALL_OPERATORS_FAIL = 'GET_ALL_OPERATORS_FAIL';

export const GET_OPERATOR_BY_ID_REQUEST = 'GET_OPERATOR_BY_ID_REQUEST';
export const GET_OPERATOR_BY_ID_SUCCESS = 'GET_OPERATOR_BY_ID_SUCCESS';
export const GET_OPERATOR_BY_ID_FAIL = 'GET_OPERATOR_BY_ID_FAIL';
