export const GET_PLATE_GRATINGS_TOLERANCES_REQUEST =
  'GET_PLATE_GRATINGS_TOLERANCES_REQUEST';
export const GET_PLATE_GRATINGS_TOLERANCES_SUCCESS =
  'GET_PLATE_GRATINGS_TOLERANCES_SUCCESS';
export const GET_PLATE_GRATINGS_TOLERANCES_FAILURE =
  'GET_PLATE_GRATINGS_TOLERANCES_FAILURE';

export const GET_LEAD_PASTE_TOLERANCES_REQUEST =
  'GET_LEAD_PASTE_TOLERANCES_REQUEST';
export const GET_LEAD_PASTE_TOLERANCES_SUCCESS =
  'GET_LEAD_PASTE_TOLERANCES_SUCCESS';
export const GET_LEAD_PASTE_TOLERANCES_FAILURE =
  'GET_LEAD_PASTE_TOLERANCES_FAILURE';

export const GET_LEAD_PASTE_TOLERANCES_BY_ID_REQUEST =
  'GET_LEAD_PASTE_TOLERANCES_BY_ID_REQUEST';
export const GET_LEAD_PASTE_TOLERANCES_BY_ID_SUCCESS =
  'GET_LEAD_PASTE_TOLERANCES_BY_ID_SUCCESS';
export const GET_LEAD_PASTE_TOLERANCES_BY_ID_FAILURE =
  'GET_LEAD_PASTE_TOLERANCES_BY_ID_FAILURE';

export const LEAD_PASTE_TOLERANCES_BY_ID_UPDATE_REQUEST =
  'LEAD_PASTE_TOLERANCES_BY_ID_UPDATE_REQUEST';
export const LEAD_PASTE_TOLERANCES_BY_ID_UPDATE_SUCCESS =
  'LEAD_PASTE_TOLERANCES_BY_ID_UPDATE_SUCCESS';
export const LEAD_PASTE_TOLERANCES_BY_ID_UPDATE_FAILURE =
  'LEAD_PASTE_TOLERANCES_BY_ID_UPDATE_FAILURE';
export const LEAD_PASTE_TOLERANCES_BY_ID_UPDATE_RESET =
  'LEAD_PASTE_TOLERANCES_BY_ID_UPDATE_RESET';

export const GET_PLATE_GRATINGS_TOLERANCES_BY_ID_REQUEST =
  'GET_PLATE_GRATINGS_TOLERANCES_BY_ID_REQUEST';
export const GET_PLATE_GRATINGS_TOLERANCES_BY_ID_SUCCESS =
  'GET_PLATE_GRATINGS_TOLERANCES_BY_ID_SUCCESS';
export const GET_PLATE_GRATINGS_TOLERANCES_BY_ID_FAILURE =
  'GET_PLATE_GRATINGS_TOLERANCES_BY_ID_FAILURE';

export const PLATE_GRATINGS_TOLERANCES_BY_ID_UPDATE_REQUEST =
  'PLATE_GRATINGS_TOLERANCES_BY_ID_UPDATE_REQUEST';
export const PLATE_GRATINGS_TOLERANCES_BY_ID_UPDATE_SUCCESS =
  'PLATE_GRATINGS_TOLERANCES_BY_ID_UPDATE_SUCCESS';
export const PLATE_GRATINGS_TOLERANCES_BY_ID_UPDATE_FAILURE =
  'PLATE_GRATINGS_TOLERANCES_BY_ID_UPDATE_FAILURE';
export const PLATE_GRATINGS_TOLERANCES_BY_ID_UPDATE_RESET =
  'PLATE_GRATINGS_TOLERANCES_BY_ID_UPDATE_RESET';

export const PLATE_GRATINGS_TOLERANCES_CREATE_REQUEST =
  'PLATE_GRATINGS_TOLERANCES_CREATE_REQUEST';
export const PLATE_GRATINGS_TOLERANCES_CREATE_SUCCESS =
  'PLATE_GRATINGS_TOLERANCES_CREATE_SUCCESS';
export const PLATE_GRATINGS_TOLERANCES_CREATE_FAIL =
  'PLATE_GRATINGS_TOLERANCES_CREATE_FAIL';
export const PLATE_GRATINGS_TOLERANCES_CREATE_RESET =
  'PLATE_GRATINGS_TOLERANCES_CREATE_RESET';

export const LEAD_PASTE_TOLERANCES_CREATE_REQUEST =
  'LEAD_PASTE_TOLERANCES_CREATE_REQUEST';
export const LEAD_PASTE_TOLERANCES_CREATE_SUCCESS =
  'LEAD_PASTE_TOLERANCES_CREATE_SUCCESS';
export const LEAD_PASTE_TOLERANCES_CREATE_FAIL =
  'LEAD_PASTE_TOLERANCES_CREATE_FAIL';
export const LEAD_PASTE_TOLERANCES_CREATE_RESET =
  'LEAD_PASTE_TOLERANCES_CREATE_RESET';
