export const GET_PLATE_GRATINGS_TOLERANCES_REQUEST =
  'GET_PLATE_GRATINGS_TOLERANCES_REQUEST';
export const GET_PLATE_GRATINGS_TOLERANCES_SUCCESS =
  'GET_PLATE_GRATINGS_TOLERANCES_SUCCESS';
export const GET_PLATE_GRATINGS_TOLERANCES_FAILURE =
  'GET_PLATE_GRATINGS_TOLERANCES_FAILURE';

export const GET_LEAD_PASTE_TOLERANCES_REQUEST =
  'GET_LEAD_PASTE_TOLERANCES_REQUEST';
export const GET_LEAD_PASTE_TOLERANCES_SUCCESS =
  'GET_LEAD_PASTE_TOLERANCES_SUCCESS';
export const GET_LEAD_PASTE_TOLERANCES_FAILURE =
  'GET_LEAD_PASTE_TOLERANCES_FAILURE';
